# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
    file: .gitpod.dockerfile

# Change checkout location to match for GOPATH
checkoutLocation: "go/src/go-swagger-example-in-gitpod/"
workspaceLocation: "go/src/go-swagger-example-in-gitpod/"
# Ports to expose on workspace startup (optional)

tasks:
 - init: swagger generate server -f swagger.yml && go get ./...
 - command: go install ./cmd/a-todo-list-application-server/ && $GOPATH/bin/a-todo-list-application-server --port 8765
