# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
    file: .gitpod.dockerfile

# Change checkout location to match for GOPATH
checkoutLocation: "go/src/"
workspaceLocation: "go/src/"
# Ports to expose on workspace startup (optional)
