consumes:
- application/json
info:
  title: Go Swagger Example
  version: 0.1.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
paths:
  /items:
    get:
      tags:
        - todos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - todos
      parameters:
        - name: item
          in: body
          schema:
            $ref: '#/definitions/item'
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/error"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error"
definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string